import base64

content_b64 = "ZGVmIG1hcF90b3BpY19jYXRlZ29yeShyYXdfdG9waWM6IHN0cikgLT4gc3RyOgogICAgaWYgbm90IHJhd190b3BpYzogcmV0dXJuICJFZ3nDqWIiCiAgICB0ID0gc3RyKHJhd190b3BpYykubG93ZXIoKQogICAgCiAgICBpZiBhbnkoeCBpbiB0IGZvciB4IGluIFsic8O8cmfFkXMiLCAiZsOhaiIsICJwYW5hc3oiLCAiZ3l1bGxhZMOhcyIsICJ2w6lyemlrIiwgImxldMO2cnQiLCAia2llc2V0dCIsICJzw7xyZ8WRc3PDqWdpIiwgImR1enphbmF0Il0pOgogICAgICAgIHJldHVybiAiU8O8cmfFkXMgcGFuYXN6IgogICAgaWYgYW55KHggaW4gdCBmb3IgeCBpbiBbImtvbnRyb2xsIiwgInZhcnJhdHN6ZWTDqXMiLCAidmlzc3phcmVuZGVsw6lzIiwgImvDqXPFkWJiaSIsICJmb2x5dGF0w6FzIl0pOgogICAgICAgIHJldHVybiAiS29udHJvbGwgaWTFkXBvbnQiCiAgICBpZiBhbnkoeCBpbiB0IGZvciB4IGluIFsiaWRFkXBvbnQiLCAiZm9nbGFsw6FzIiwgImJlamVsZW50a2V6w6lzIiwgImxlbW9uZGFzIiwgIm3Ds2Rvc8OtdMOhcyIsICJib29raW5nIl0pOgogICAgICAgIHJldHVybiAiSWRFkXBvbnRmb2dsYWzDoXMiCiAgICBpZiBhbnkoeCBpbiB0IGZvciB4IGluIFsiw6FyIiwgIm1lbm55aSIsICJrw7ZsdHPDqWciLCAiYWrDoW5sYXQiLCAiZml6ZXRDqXMiLCAiYWtjacOzIiwgInLDqXN6bGV0Zml6ZXTDqXMiXSk6CiAgICAgICAgcmV0dXJuICLDgXJrw6lyZMOpcyIKICAgIGlmIGFueSh4IGluIHQgZm9yIHggaW4gWyJueWl0dmEiLCAiw7NyYSIsICJtaWtvciIsICJyZW5kZWzDqXNpIGlkxZEiLCAicmVuZGVsw6lzIl0pOgogICAgICAgIHJldHVybiAiTnlpdHZhdGFydMOhcyIKICAgIGlmICJlbWFpbCIgaW4gdCBvciAiZS1tYWlsIiBpbiB0IG9yICJtYXJrZXRpbmciIGluIHQgb3IgIm7DtnZlbGplIiBpbiB0IG9yICJow61ybGV2w6lsIiBpbiB0OgogICAgICAgIHJldHVybiAiRS1tYWlsIG1lZ2tlcmVzw6lzIgogICAgCiAgICByZXR1cm4gIsOBbHRhbMOhbm9zIMOpcmRla2zFkWTDqXMi"

handover_b64 = "ICAgICAgICBoYW5kb3Zlcl9jb3VudHMgPSB7CiAgICAgICAgICAgICLDllNzemV0ZXR0IGvDqXJkw6lzIjogMCwKICAgICAgICAgICAgIlPDvHJnxZFsIC8gdHJpw6F6cyI6IDAsCiAgICAgICAgICAgICJIacOhbnl6w7MgaW5mbyI6IDAsCiAgICAgICAgICAgICJGb2dsYWzDoXNpIGtpdsOpdGVsIjogMCwKICAgICAgICAgICAgIkVtYmVyaSBkw7ZudMOpcyI6IDAKICAgICAgICB9"

replacement_1 = base64.b64decode(content_b64).decode('utf-8') + '\n'
replacement_2 = base64.b64decode(handover_b64).decode('utf-8') + '\n'

with open('database.py', 'r', encoding='utf-8') as f:
    lines = f.readlines()

lines[407:425] = [replacement_1]
lines[457:464] = [replacement_2]

with open('database.py', 'w', encoding='utf-8') as f:
    f.writelines(lines)
