-- 2026-09-22: Változási napló (ügyfélprofil + kapcsolódó interakciók)
-- Ki/mikor/mire módosított — a profil „Változási napló" modalja olvassa.
-- STAGINGEN lefutott (Management API). PROD-deploynál KÖTELEZŐ futtatni!
CREATE TABLE IF NOT EXISTS public.client_change_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id uuid REFERENCES public.tenants(id),
  client_id bigint NOT NULL,
  actor text NOT NULL DEFAULT 'eaisyDesk',
  action text NOT NULL,
  label text NOT NULL,
  new_value text,
  related_ref text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_client_change_log_client ON public.client_change_log (client_id, created_at DESC);
ALTER TABLE public.client_change_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "service_role_full_access" ON public.client_change_log FOR ALL USING (true) WITH CHECK (true);
