; ============================================================
; Asterisk logger konfig – részletes naplózás
; ============================================================
[general]
dateformat=%F %T

[logfiles]
console => notice,warning,error,verbose(3)
/var/log/asterisk/full => notice,warning,error,debug,verbose,dtmf
/var/log/asterisk/error => error
