[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_media_address=165.227.139.84
external_signaling_address=165.227.139.84

; ── Telefonalo.hu ────────────────────────────────────────────
[telefonalo-auth]
type=auth
auth_type=userpass
username=3617001622
password=wOw9nfnlIg

[telefonalo-aor]
type=aor
contact=sip:3617001622@sbc2.opennet.hu:5060
qualify_frequency=30

[telefonalo]
type=endpoint
transport=transport-udp
context=from-telefonalo
disallow=all
allow=ulaw
allow=alaw
aors=telefonalo-aor
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
from_user=3617001622
from_domain=sbc2.opennet.hu
direct_media=no

[telefonalo-reg]
type=registration
transport=transport-udp
outbound_auth=telefonalo-auth
server_uri=sip:sbc2.opennet.hu
client_uri=sip:3617001622@sbc2.opennet.hu
expiration=60
line=yes
endpoint=telefonalo

[telefonalo-identify]
type=identify
endpoint=telefonalo
match=91.223.222.0/24
match=91.223.221.0/24

; ── LiveKit visszahívás fogadása (LiveKit → Asterisk) ────────
[livekit-cb-identify]
type=identify
endpoint=livekit-cb
match=161.115.161.0/24

[livekit-cb]
type=endpoint
context=from-livekit
disallow=all
allow=ulaw
allow=alaw
direct_media=no
